AWSTemplateFormatVersion: '2010-09-09'
Description: VPC Peering between two VPCs in the same account and region

Parameters:
  VpcAId:
    Type: AWS::EC2::VPC::Id
    Description: The ID of the first VPC 

  VpcBId:
    Type: AWS::EC2::VPC::Id
    Description: The ID of the second VPC 

  VpcACidr:
    Type: String
    Description: CIDR block of VPC A

  VpcBCidr:
    Type: String
    Description: CIDR block of VPC B

  VpcARouteTableExportName:
    Type: String
    Description: Export name of VPC A's private route table 

  VpcBRouteTableExportName:
    Type: String
    Description: Export name of VPC B's private route table 

Resources:
  VPCPeeringConnection:
    Type: AWS::EC2::VPCPeeringConnection
    Properties:
      VpcId: !Ref VpcAId
      PeerVpcId: !Ref VpcBId
      Tags:
        - Key: Name
          Value: !Sub "${VpcAId}-${VpcBId}-peering"

  RouteFromVpcAToVpcB:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId:
        Fn::ImportValue: !Ref VpcARouteTableExportName
      DestinationCidrBlock: !Ref VpcBCidr
      VpcPeeringConnectionId: !Ref VPCPeeringConnection

  RouteFromVpcBToVpcA:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId:
        Fn::ImportValue: !Ref VpcBRouteTableExportName
      DestinationCidrBlock: !Ref VpcACidr
      VpcPeeringConnectionId: !Ref VPCPeeringConnection

Outputs:
  PeeringConnectionId:
    Description: The ID of the VPC Peering Connection
    Value: !Ref VPCPeeringConnection
